version: "3.9"

services:
  ZMQ_JWT:
    build: ZMQ_JWT
    command: ["python", "-u", "./ZMQ_JWT.py"]
    environment:
      SERVER_LISTEN_URI: tcp://0.0.0.0:3001
      SERVER_CONNECT_URI: tcp://0.0.0.0:3000
    networks:
      mynet:
        aliases:
          - ZMQ_JWT
