version: '3'
services:
  zmq:
    build: "./zmq"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - ZMQ_ADDRESS=tcp://0.0.0.0:5556
  zmqtest:
      build: "./zmqtest"
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        - ZMQ_ADDRESS=tcp://zmq:5556