version: '3'
services:
  zmq:
    build: "./zmq"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - ZMQ_ADDRESS=tcp://0.0.0.0:5556
      - ZMQ_ADDRESS_2=tcp://0.0.0.0:5555
      - ZMQ_ADDRESS_3=tcp://0.0.0.0:5557
  zmqtest:
      build: "./zmqtest"
      depends_on:
        - zmq
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      environment:
        - ZMQ_ADDRESS=tcp://zmq:5556
        - ZMQ_ADDRESS_2=tcp://zmq:5555
